### ISSUE TITLE
Release VILLASnode to the wild

### ISSUE THREAD

**Issue by stv0g** [VILLASframework/node#48]
To attract more users and their contributions we should release VILLASnode as open-source software.

I am currently in the progress of replacing non-BSD compliant dependencies with MIT/BSD licensed libraries.

**Sub-tasks:**

* [x]  Pick an open-source license (#56)
* [x] Add license information to source files (!13)
* [x] Get documentation in shape (#57)
* [x] Find way for distribution & accepting external contributions (#58)
